name: Pre-Merge Checks

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      # Run tests or linters
      - name: Run Tests
        run: |
          ./mvnw clean install